### ISSUE TITLE
SSL login https lets encrypt

### ISSUE THREAD

**Issue by dcmorse** [contradb/contra#69]
@strongjz: "for contra, you should use SSL for the log in"..."You need an SSL cert to encrypt the traffic"
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

**Comment by dcmorse** [comment]
https://letsencrypt.org/

**Comment by dcmorse** [comment]
cert email goes to `contradb.admonsterator` at an overwhelmingly popular supposedly non-evil-being webmail provider.

**Comment by dcmorse** [comment]
```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/contradb.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/contradb.com/privkey.pem
   Your cert will expire on 2018-09-29. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by dcmorse** [comment]
# I followed these instructions:
https://certbot.eff.org/lets-encrypt/ubuntutrusty-nginx
except I skipped this part because it seems wrong/unbelievable that arguably the world's most popular distro isn't supported four years later. Also, when I clicked the docker link, it was full of warnings not to use it. So I didn't. 

> Certbot's DNS plugins which can be used to automate obtaining a wildcard certificate from Let's Encrypt's ACMEv2 server are not available for your OS yet. This should change soon but if you don't want to wait, you can use these plugins now by running Certbot in Docker instead of using the instructions on this page. 

And then I also skipped the "Automating Renewal" section, because why renew something that doesn't work. 

When I restart nginx and hit the site, it hangs forever:

```
dm@black develop ~/contra$ curl -L -v contradb.com
* Rebuilt URL to: contradb.com/
*   Trying 45.55.252.228...
* Connected to contradb.com (45.55.252.228) port 80 (#0)
> GET / HTTP/1.1
> Host: contradb.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.4.6 (Ubuntu)
< Date: Sun, 01 Jul 2018 15:59:03 GMT
< Content-Type: text/html
< Content-Length: 193
< Connection: keep-alive
< Location: https://contradb.com/
< 
* Ignoring the response-body
* Connection #0 to host contradb.com left intact
* Issue another request to this URL: 'https://contradb.com/'
* Found bundle for host contradb.com: 0x55f9dbf5d330 [can pipeline]
*   Trying 45.55.252.228...
^C
dm@black develop ~/contra$ curl -L -v https://contradb.com
* Rebuilt URL to: https://contradb.com/
*   Trying 45.55.252.228...
^C
dm@black develop ~/contra$ curl -L -v https://contradb.com/
*   Trying 45.55.252.228...
^C
dm@black develop ~/contra$ echo 'restore config and it started working again'
restore config and it started working again
```
Then I checked the instructions against this:
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04
They seem pretty equivalent. So I'm stuck.

**Comment by dcmorse** [comment]
My firewall was blocking 443. 

Huzzah!

**Comment by dcmorse** [comment]
Had to disable because of #439

**Comment by dcmorse** [comment]
* https://github.com/plataformatec/devise/wiki/How-To:-Use-SSL-(HTTPS) is the `X-FORWARDED-PROTO` properly set? It sure doesn't look like it. 
* maybe still has something to do with `config.force_ssl = true`, see e17e9c87635fcc9407deaa4fe8cc8735fb4ceed3

**Comment by dcmorse** [comment]
gonna try https://www.digitalocean.com/community/questions/how-do-i-configure-ssl-on-nginx-for-rails-application
```
proxy_set_header X-Forwarded-Proto $scheme;
```
will update this post with result

**Comment by dcmorse** [comment]
### todo
- [ ] successfully push 9f974c8d174db86d4dff9ebf7b485b310fc5c7fe from my laptop (random git issues!)
- [ ] revert `config/environments/production.rb` on production
- [ ] deploy the push above
- [ ] do the certificate auto-renewal things

**Comment by dcmorse** [comment]
final `rails-https-forwarded-proto` with tweak to make www.contradb.com forward to https://contradb.com
```
rails@contradb:/etc/nginx/sites-available$ cat rails-https-forwarded-proto
upstream app {
    # Path to Unicorn SOCK file, as defined https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-unicorn-and-nginx-on-ubuntu-14-04
    server unix:/home/rails/contra/shared/sockets/unicorn.sock fail_timeout=0;
}

# from https://www.digitalocean.com/community/tutorials/how-to-redirect-www-to-non-www-with-nginx-on-ubuntu-14-04
server {
    server_name www.contradb.com;
    return 301 https://contradb.com$request_uri;
}

server {
  root /home/rails/contra/public;
  server_name contradb.com;
  index index.htm index.html;

  location / {
    try_files $uri/index.html $uri.html $uri @app;
  }

  # doesn't appear to serve the fingerprinted assets the way I want it to - Dave Morse contradb
  # see https://github.com/dcmorse/contra/issues/24
  location ~ ^/assets/ {
    expires 1y;
    add_header Cache-Control public;

    add_header ETag "";
    break;
  }

  location ~* ^.+\.(jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|mp3|flv|mpeg|avi)$ {
    try_files $uri @app;
  }

  location @app {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://app;
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/contradb.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/contradb.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = contradb.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen   80;
  server_name contradb.com;
    return 404; # managed by Certbot


}

```
